### ISSUE TITLE
Request 

### ISSUE THREAD

**Issue by alpapak** [mozzwald/x728-daemon#1]
Nice project, i was trying to find request but i didn't find so i am posting here.

Can you add, send email if power off and power back on?
Is it working and test it with the latest pi os?

I am newbie in coding.

**Comment by mozzwald** [comment]
> Can you add, send email if power off and power back on?

I do not have plans for adding features like that, sorry. You are welcome to try yourself.

> Is it working and test it with the latest pi os?

I am running it with Raspbian 10
